platform :ios, '10.0'

target 'AXPhotoViewerExample' do

  use_frameworks!

  pod 'Reveal-SDK'

  # SDWebImage
  pod 'SDWebImage/GIF'

  # AXPhotoViewer
  pod 'AXPhotoViewer/SDWebImage’, :path => '../AXPhotoViewer.podspec'

end
