platform :ios, '10.0'

target 'AXPhotoViewerExample' do

  use_frameworks!

  pod 'Reveal-SDK'

  # Loading spinner
  pod 'DRPLoadingSpinner'

  # AXPhotoViewer
  pod 'AXPhotoViewer', :path => '../../AXPhotoViewer.podspec'

end
